3강 서현 완료
AUSG/aws-certification-study pull request #7
Opened 2019-10-11 09:20 UTC by seohyun0120

3강 다 들었습니다

2019-10-15 07:05 UTC, yoonhoGo approved these changes

2019-10-15 12:00 UTC, byunjuneseok approved these changes
yay-!

2019-10-16 01:10 UTC, yoonhoGo requested changes
docs/3강/SUMMARY.md -> docs/module2/SUMMARY.md
경로 바꿔주세요

2019-10-16 13:15 UTC, seohyun0120 commented
@yoonhoGo 리뷰해주세요

2019-10-17 02:12 UTC, yoonhoGo approved these changes

2019-10-17 02:13 UTC, merged